name: Automation CI
on: [push]
jobs:
  automation:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.35.1-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Start the app"
          ./shopping-store-linux-amd64 &
          echo "Install dependencies from lockfile"
          npm ci
          echo "Run tests"
          npm run test:ci