name: Playwright Tests
on:
  push:
    branches: [master]
jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@2
      - name: Say Hello
        run: echo Hello