name: Playwright Tests
on:
  push:
    branches: [master]
jobs:
  playwrighttests:
    runs-on: ubuntu-laatest
    steps:
      - name: Checkout repository
        uses: actions/checkout@2
      - name: Say Hello
        run: echo Hello